### ISSUE TITLE
What is a channel?

### ISSUE THREAD

**Issue by MartinThoma** [OpenBCI/OpenBCI_Python#22]
Is a channel one electrode?

**Comment by jfrey-xx** [comment]
It's not the same but basically, yes, with OpenBCI *most of the time* a channel is connected to an electrode (you could plug in fact any kind of analog sensor).

Are we using somewhere in this repository confusing terms, or... can I close this "bug"?

**Comment by teonlamont** [comment]
hi @MartinThoma, fancy seeing you here :)

**Comment by MartinThoma** [comment]
@jfrey-xx No, it can be closed.  I'm sorry I asked it here, but I didn't know where else I should ask. And I also think this might be helpful for other people looking for the term in this context.

@teonlamont Haha, the world is small :-)

**Comment by jfrey-xx** [comment]
No problem, the issue tracker is indeed helpful for those kind of messages ;)

If you have general questions about the device or EEG, don't hesitate to visit OpenBCI's forum!
