### ISSUE TITLE
yapsy logger not set when plugin search begins

### ISSUE THREAD

**Issue by qwer1304** [OpenBCI/OpenBCI_Python#23]
In user.py, yapsy logger is not set when collectPlugins is called. Therefore, instead of a meaningful error messages there's a cryptic message about there being no handler for yapsy.
Easy to fix by adding e.g. logging.basicConfig(level=logging.ERROR) before calling yapsy.

**Comment by teonlamont** [comment]
thanks for the suggestions, pr is welcome :)
