### ISSUE TITLE
sample output meaning

### ISSUE THREAD

**Issue by Nikre93** [OpenBCI/OpenBCI_Python#25]
Hi everybody, i have only a question: when i run the test.py, those value that print, what rapresent?

**Comment by teonbrooks** [comment]
maybe @rceballos98 might know?

**Comment by teonbrooks** [comment]
my guess is values in microvolts, but I'm not 100%

**Comment by Nikre93** [comment]
Those values are always negative and very high...  I think that the openBCI Gui make another processing of data.. I can wrong..

**Comment by rceballos98** [comment]
Hi Nike, 
Teon is correct, they are microvolts values for the voltage difference between each electrode and the reference electrode. If they are very negative and high it might be on eof 2 reasons. 
1) that's actually the real value and what you are used to looking at from the processing GUI is one where the baseline or DC offset has been removed. This can be done by applying a high pass filter to the signal. 
2) there's an issue either with the board or the electrode placement. If the GUI seems fine though, it's probably option 1.

**Comment by Nikre93** [comment]
Very Thankful...  With your input I found in github the EEGrunt that do what you say...  I'm working on..
