### ISSUE TITLE
pyOSC doesn't work with Python 3

### ISSUE THREAD

**Issue by gabrielibagon** [OpenBCI/OpenBCI_Python#30]
I tried to install pyOSC with Python 3, and there are a lot of compatibility issues (using the version installed via pip + requirements.txt). We could rewrite parts of the module and include the file in the repository, or we could find another library that is more compatible with Python 2.7 and Python 3.

I'll be looking into a fix myself, but I wanted to shout this out there in case someone has insight.

**Comment by RenaudWasTaken** [comment]
Hey !

I am actually using this with python 3 :D
I've had the same issue as you had but after using the 2to3 binary on pyOSC source
there were only a few minor fix left :D

I there a real need for python 3 if so I could probably help

**Comment by RenaudWasTaken** [comment]
If anyone is interested I made a pull request here: https://github.com/ptone/pyosc/pull/7

You can clone my python3 fork of the pyOSC repo here:
https://github.com/RenaudWasTaken/pyosc/tree/python3

**Comment by micuat** [comment]
It seems pyOSC has not been not maintained so you should consider switching to python-osc (they support python3 and has better API). It should be fairly simple to switch but currently I'm having issues with my sd card on raspberry pi so I won't be able to send a pull request :(
