### ISSUE TITLE
2's complement 24->32 bits conversion

### ISSUE THREAD

**Issue by atom2626** [OpenBCI/OpenBCI_Python#37]
I borrowed your implementation of conv24bitsToInt (referenced your name/work)

However I think:
if (unpacked[0] >= 127):

Should be replaced by 
if (unpacked[0] > 127):

has 127 is written 0111 1111, sign bit is off.

**Comment by jfrey-xx** [comment]
Wow, nice catch! Thanks for the fix, it's committed now :)

**Comment by atom2626** [comment]
No problem
