### ISSUE TITLE
plugins initialization failed

### ISSUE THREAD

**Issue by qasimwasfi** [OpenBCI/OpenBCI_Python#61]
after running user.py script  ,when i add the plugins like by typing add print,  i get message" initialization failed ,could not find Fat16/32 partition".i have every thing alright ,Sdcard is inserted and format is fat 32.
  i am running this on Raspbian OS at Raspberry pie 3.python version is 2.7.i haive plugged in usb dongle of  openbci in rasppberry pie 3.

i have attached the snapshot below.
![errors](https://user-images.githubusercontent.com/15672665/38328873-78f2829e-3865-11e8-8c2a-a870fd31548e.jpg)

**Comment by qasimwasfi** [comment]
i was running user.py from python idle gui before,however error was resolved via sudo python user.py -p /dev/ttyUSB0 --add print command from raspbian terminal

**Comment by jfrey-xx** [comment]
Hello,

Sorry for the late response, indeed, you cannot add plugins on the fly, the "add" is a flag to pass to the command line interface.

Being able to load/unload plugins after init could be a nice feature though!
