### ISSUE TITLE
Form of data

### ISSUE THREAD

**Issue by LaraibMahboob** [OpenBCI/OpenBCI_Python#62]
I want to know that data return in test.py is in which form?

**Comment by jfrey-xx** [comment]
The formatting is quite arbitrary, each sample separate by dashes lines, then 3 lines with: sample number, EEG channels, AUX data. 

It's straightforward to change that to whatever you need by customizing the `printData` function, it's really just an example to show the most basic way to acquire data -- and I realize that the test script is somewhat duplicated, `./test_log.py` and `./scripts/test.py`.
