### ISSUE TITLE
Sampling Frequency

### ISSUE THREAD

**Issue by LaraibMahboob** [OpenBCI/OpenBCI_Python#65]
What is frequency of samples in test.py ?

**Comment by jfrey-xx** [comment]
As for the rest of the framework here, it will depends on board configuration, and on the board you are using. For the Ganglion: 200hz, for the Cyton: 250Hz for 8 channels, and if the daisy module is installed it runs at 125Hz. If you have more question about the script, comment below, even if I'll close this "issue" ;)
