### ISSUE TITLE
python on windows

### ISSUE THREAD

**Issue by Conijiwa** [OpenBCI/OpenBCI_Python#72]
I want to run this code on windows Os, and I find on the following website in DEPENDENCIES part, that it says that "To use a Windows OS, change the “__init“ function in open_bci_v3.py to establish a serial connection in Windows". However, I don't unnderstand how to change this function. Can anyone help me? Thanks for your help.
http://docs.openbci.com/OpenBCI%20Software/05-OpenBCI_Python

**Comment by jfrey-xx** [comment]
Hello,

Did you try using the "user.py" script and changing the serial port to a more "windows" one -- i.e. tune the `python user.py -p /dev/ttyUSB0` example?

**Comment by LarissaBruebach** [comment]
Hello,
we are currently trying to run this on Windows. Unfortunatly when trying to change the port with the command you suggested we get the error: "ModuleNotFoundError: No module named 'bluepy'". Bluepy is not available for windows.

Were you able to get it to run on windows? If so, what did you change?

Thanks in advance,
Lara
