### ISSUE TITLE
python 3 incompatibility: wifi.py and utils/ssdp.py

### ISSUE THREAD

**Issue by dyfer** [OpenBCI/OpenBCI_Python#82]
Despite https://github.com/OpenBCI/OpenBCI_Python/pull/71 it seems that wifi streaming is still not fully compatible with python 3 (tested on macOS 10.12, python 3.6.5).

Submitting this PR I came across https://github.com/OpenBCI/OpenBCI_Python/pull/78 which fixes this for me.

**Comment by andrewjaykeller** [comment]
Closing this because of #78
