### ISSUE TITLE
execute make -C ./bluepy clean error: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by digitalgreentea** [OpenBCI/OpenBCI_Python#86]
I am installing bluepy and this error shows up every time I run pip install bluepy or run python setup.py install inside the bluepy folder.

[http://tinypic.com/r/2q09ks7/9](http://tinypic.com/r/2q09ks7/9)

Can anyone help?

**Comment by shenjianaixuexi** [comment]
hello，have  you solved the problem ？ can U give me some advice

**Comment by hack-r** [comment]
I'm not sure of the full context of this thread, just got this on my mobile email, but based on the screen shot it looked like a posaible Windows Bluetooth driver problem with bluepy. Remember, Windows has it's own proprietary Bluetooth drivers/language that's totally incompatible with open standards, bc some combination of they hate you and think they are better than you.

i know you can replace Windows drivers with Zadig (so?). that may cause you other Bluetooth problems tho just FYI. I would need to go check further on what I did on Windows in the past but it should work on Linux if that's an option or try the tool
